### ISSUE TITLE
Game breaking bugs that make the game quite unplayable.

### ISSUE THREAD

**Issue by Rezpit** [parkour-tf/ParkourFortress-Redux#4] opened 2022-02-15 15:39 UTC
I'm no bizaitch to complain, I personally love parkour fortress, but I can't say I haven't found some trouble along the way. Found bugs that need fixing quite bad...

-  First of all, the map pool is incomplete / some maps are missing, but yet they are counted as incomplete, therefore noone can achieve 100% of finished maps. (the maps in question are dark meat, darker meat, repairkour b9, acrasia b5 acrasia r1, and offshore v9_1)

- Second of all, wallrun range is shortened. Usually that'd be a good thing, but considering bonuses for not so nuance are impossible because of this "change", i think the way to fix this is either:
a) Change back the wallrun range (Recommended, takes less time and less effort)
b) Change the maps

- Then I found this bug - when you die, while taunting, and you respawn, you die immideatly.

- I think last bug I found is, when you rtv for a map, join any team, wait for the "Waiting for players" to run out, slide to gain speed, your speed automatically sets to 0. This happened alot on Sakura, Mandrillmaze, Mizuki and Not so Nuance.

Now I got some... other bugs that've been there since day 1 but not sure if they're intentionally left there.
- Wall lunging
- Jumping high when climbing a wall and hanging
- Trying to wallrun makes you jump off the wall sometimes

Welp, that's it. Incase needed, I can make a video showing the bugs. Add me on Discord - ПΛƬΣ#9157

**Comment by ScrewdriverHyena** [comment] 2022-09-05 16:45
@LucasNimny Can you verify if these are still an issue?

**Comment by ZwipZwapZapony** [comment] 2022-10-18 20:45
I don't know how to test the first and second issues.

The third one (dying while taunting making you die when respawning) only seems to happen when killed by "in-level" instant-death triggers (instant-death water, "electric" fences, et cetera, but *not* sawblades), not when suiciding or dying from fall damage (whether "normal" or "death-from-fall" fall damage).

I think that I reproduced the fourth issue, losing all speed (and having to let go of W and press it again to move again), by trying to use `sm_boost` shortly after a round started (specifically on Darker Meat). I couldn't reproduce it by sliding in Mandrillmaze, though.

**Comment by Rezpit** [comment] 2022-11-03 09:17
> I don't know how to test the first and second issues.

I believe testing the maps I put there as a reference is a way to test the issue.

> The third one (dying while taunting making you die when respawning) only seems to happen when killed by "in-level" instant-death triggers (instant-death water, "electric" fences, et cetera, but _not_ sawblades), not when suiciding or dying from fall damage (whether "normal" or "death-from-fall" fall damage).

Not true. While I use the Boston Boarder(https://wiki.teamfortress.com/wiki/Boston_Boarder) taunt, then I press my kill bind, when I respawn, I die with 1 HP left for some reason. I can provide video evidence if needed. :)

**Comment by horiuchii** [comment] 2023-05-10 21:24
Closing this issue as its invalid / outdated. If you find that these problems are still unresolved, feel free to create separate issues per problem that you find.

**Closed by horiuchii** 2023-05-10 21:24 UTC
Labels: bug, help wanted
